### PR TITLE
Add scrolling as inputs to media-player

### PR DESCRIPTION
**Pull request by DrWursterich**
the default is to increase/decrease the volume by 5%

### CODE REVIEW

**Comment by kgilmer** [comment]
Sorry it's taken quite awhile before I could get to this @DrWursterich .  Looks good, but can you describe briefly what testing you've done?

**Comment by DrWursterich** [comment]
No worries.
The only testing I did is using it on my private and work pc. If there is an actual test I can provide please let me know; I'd be happy to run/write it.

**Comment by kgilmer** [comment]
That works for me given the complexity of the change, thanks @DrWursterich !

**Review by kgilmer — APPROVED** [review]
LGTM

**Pull request merged**
