### PR TITLE
Added script mediaplayer2 with pango markup and font awesome glyphs

### PR DESCRIPTION
**Pull request by Interesting-name**

### CODE REVIEW

**Comment by kgilmer** [comment]
Looks very clean @Interesting-name !  I will test tonight and update.

**Comment by kgilmer** [comment]
It doesn't look like there is an Ubuntu package for playerctl.  When I run the script I get an error that the command doesn't exist and I didn't find a package in the default Ubuntu repositories.  I did [find this](https://bazaar.launchpad.net/~ubuntu-branches/debian/sid/playerctl/sid/files), so it should not be difficult to port to Ubuntu but that will need to be done and hosted in the Regolith PPA before this script can be merged.  I can work on that as part of speed-ricer later in the week.  I'll update here when there is a package available for testing.

**Comment by kgilmer** [comment]
I found an Ubuntu package for playerctl, but only for Cosmic: https://launchpad.net/ubuntu/+source/playerctl/0.6.1-1

Easier to add this to Regolith than building a new package based on the Debian version.

**Comment by kgilmer** [comment]
The latest version of the package requires a build tool version not available in Bionic. What version of playerctl are you using @interesting-name?

**Comment by Interesting-name** [comment]
Hey @kgilmer 

My version is 2.0.2 and I think I got it from the official ubuntu repositories (via `apt-get install playerctl`).

Some info:
`dpkg -s playerctl` yields this:
```
Package: playerctl
Status: install ok installed
Priority: optional
Section: sound
Installed-Size: 64
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Version: 2.0.2-1
Depends: libc6 (>= 2.4), libglib2.0-0 (>= 2.39.90), libplayerctl2 (>= 2.0.2), dbus
Suggests: audacious, cmus, mopidy, mpd, quodlibet, rhythmbox-plugins, vlc, xmms2
Enhances: awesome, i3-wm, xmonad
Description: utility to control media players via MPRIS
 Playerctl is a command-line utility and library for controlling media players
 that implement the MPRIS D-Bus Interface Specification. Compatible players
 include audacious, cmus, mopidy, mpd, quod libet, rhythmbox, spotify, vlc and
 xmms2.
 .
 Playerctl makes it easy to bind player actions, such as play and pause,
 to media keys. Playerctl also provides an introspectable library accessible
 in many popular scripting languages that allows more detailed control like
 the ability to subscribe to media player events or get metadata such as
 artist and title for the playing track.
Original-Maintainer: Debian Multimedia Maintainers <debian-multimedia@lists.debian.org>
Homepage: https://github.com/acrisci/playerctl
```

`apt-cache showpkg playerctl` yields this:
```
Package: playerctl
Versions: 
2.0.2-1 (/var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_eoan_universe_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_eoan_universe_binary-amd64_Packages
                  MD5: eee9d896b54f5574dca7264a9b169129
 Description Language: 
                 File: /var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_eoan_universe_binary-i386_Packages
                  MD5: eee9d896b54f5574dca7264a9b169129
 Description Language: en
                 File: /var/lib/apt/lists/de.archive.ubuntu.com_ubuntu_dists_eoan_universe_i18n_Translation-en
                  MD5: eee9d896b54f5574dca7264a9b169129


Reverse Depends: 
  playerctl:i386,playerctl
Dependencies: 
2.0.2-1 - libc6 (2 2.4) libglib2.0-0 (2 2.39.90) libplayerctl2 (2 2.0.2) dbus (0 (null)) audacious (0 (null)) cmus (0 (null)) mopidy (0 (null)) mpd (0 (null)) quodlibet (0 (null)) rhythmbox-plugins (0 (null)) vlc (0 (null)) xmms2 (0 (null)) awesome (0 (null)) i3-wm (0 (null)) xmonad (0 (null)) playerctl:i386 (32 (null)) 
Provides: 
2.0.2-1 - 
Reverse Provides: 
```

**Comment by kgilmer** [comment]
Thanks @Interesting-name , yeah looks like the package is only available from 19.04 onward.

**Comment by kgilmer** [comment]
playerctl for Bionic and Disco are built into speed-ricer.  Merging script.

**Pull request merged**
