### PR TITLE
A block for monitoring net traffic

### PR DESCRIPTION
**Pull request by cheginit**
Addresses #9.

I added a script for monitoring net traffic that can be run with `sh` and used `pangeo` format for the output. Here is how the outputs looks like:
```bash
$ /usr/share/i3xrocks/nettraffic
<span font_desc="Source Code Pro Medium 13" color="#D8DEE9"> 0.0B</span><span color="#7B8394">typeface_bar_glyph_dn </span><span font_desc="Source Code Pro Medium 13" color="#D8DEE9">0.0B</span><span color="#7B8394">typeface_bar_glyph_up</span>
<span font_desc="Source Code Pro Medium 13" color="#D8DEE9"> 19.7KB</span><span color="#7B8394">typeface_bar_glyph_dn </span><span font_desc="Source Code Pro Medium 13" color="#D8DEE9">13.1KB</span><span color="#7B8394">typeface_bar_glyph_up</span>
```

Then I added the following block to `/etc/regolith/i3xrocks/config`:
```bash
[nettraffic]
#instance=wlp3s0 Replace with your wifi device if you need
interval=5
```

As well as two new entries into `/etc/regolith/styles/typeface-sourcecodepro` as follows:
```bash
....
#define typeface_bar_glyph_up ▲
#define typeface_bar_glyph_dn ▼
...
```
Still doesn't show up in the status bar though.

### CODE REVIEW

**Comment by kgilmer** [comment]
@cheginit , looking good!  I think you'll need to update it so that it outputs two lines (run another script such as wifi2 from the terminal to see what I mean), and you'll want to either have the script terminate after running once (preferred) or set the `interval` to `persist` in the i3xrocks conf.  Search for 'persist' here to get details: https://github.com/vivien/i3blocks#blocks

**Comment by cheginit** [comment]
@kgilmer I see what you mean. I modified the script, now it works with the persist interval but couldn't get the other one to work. It doesn't show the correct net traffic. You can find both scripts in my nettraffic fork:
https://github.com/cheginit/nettraffic

**Comment by kgilmer** [comment]
I tried to push a change to your repo but it didn't allow me.  I think I've seen others collaborate on PRs but am unsure of what I'm doing wrong.  In any case, I made some modifications to the script.  Forgive me for just pasting it in here but:
```
#!/bin/sh

VALUE_COLOR=${color:-$(xrescat i3xrocks.value.color "#D8DEE9")}
LABEL_COLOR=${label_color:-$(xrescat i3xrocks.label.color "#7B8394")}

VALUE_FONT=${font:-$(xrescat i3xrocks.value.font "Source Code Pro Medium 13")}

GET="cat /proc/net/dev"
LABEL=true
UPL=${label_icon:-$(xrescat i3xrocks.label.up ▲)}
DNL=${label_icon:-$(xrescat i3xrocks.label.dn ▼)}
ULEV=2
IF=`ip route get 1.1.1.1 | grep -Po '(?<=dev\s)\w+' | cut -f1 -d ' '`
IF="${BLOCK_INSTANCE:-${IF}}"

while getopts i:a:u:e:s:t:U:D:lhv option
do
  case "${option}"
  in
    i)
      IF=${OPTARG};;
    a)
      RT=${OPTARG};;
    u)
      UNIT=${OPTARG};;
    e)
      ULEV=${OPTARG};;
    s)
      SEP=${OPTARG};;
    t)
      DLY=${OPTARG};;
    l)
      LABEL=true;;
    h)
      echo -e "Usage: nettraffic [OPTION]"
      echo -e "Options:"
      echo -e "  -i  (%ifname%)\t Specify which network interface to monitor. Required."
      echo -e "  -a  (up|dn|total)\t Shows which data to display. Prints both if not used."
      echo -e "  -u  (K|KB|M|MB)\t Units to show the data in. Automatic if not specified."
      echo -e "  -e  (0|1|2|3|4)\t Level of units displayed. (0 for none, 1 for K, 2 for KB, 3 for K/s,"
      echo -e "    \t\t\t 4 for KB/s). Default if 4."
      echo -e "  -l\t\t\t Choose whether or not to display the label (up or down)."
      echo -e "  -s  (%string%)\t A separator to divide between up and down. Default is none."
      echo -e "  -t  (%integer%)\t Set the interval for the data update. Default is 1."
      echo -e "  -v\t\t\t Prints version number."
      echo -e "  -h\t\t\t Prints this help."
      echo "For full help, visit http://github.com/ma-santoso/nettrafic/"
      exit;;
    v)
      echo "$NAME, version $VERSION";
      exit;;
    *)
      exit;;
  esac
done

if [ "$IF" = "" ]; then
  echo "No interface specified"
  exit
fi

if [ "$LABEL" = true ]; then
  if [ "$UPL" = "" ]; then
    UP=" up"
  else
    UP=$UPL
  fi
  if [ "$DNL" = "" ]; then
    DN=" dn"
  else
    DN=$DNL
  fi
else
  UP=""
  DN=""
fi

if [ "$UNIT" = "MB" -o "$UNIT" = "M" ]; then
  FAC=1048576
  case "$ULEV"
  in
    0) SUF="";;
    1) SUF="M";;
    2) SUF="MB";;
    3) SUF="M/s";;
    *) SUF="MB/s";;
  esac
elif [ "$UNIT" = "KB" -o "$UNIT" = "K" ]; then
  FAC=1024
  case "$ULEV"
  in
    0) SUF="";;
    1) SUF="K";;
    2) SUF="KB";;
    3) SUF="K/s";;
    *) SUF="KB/s";;
  esac
elif [ "$UNIT" = "B" -o "$UNIT" = "" ]; then
  FAC=1
  case "$ULEV"
  in
    0) SUF="";;
    1) SUF="B";;
    2) SUF="B";;
    *) SUF="B/s";;
  esac
fi

if [ "$DLY" = "" ]; then
  DLY=1;
fi

RN="0.0"
TN="0.0"
AN="0.0"

RX1=`$GET | grep $IF | awk '{print $2}'`; TX1=`$GET | grep $IF | awk '{print $10}'`
sleep $DLY
RX2=`$GET | grep $IF | awk '{print $2}'`; TX2=`$GET | grep $IF | awk '{print $10}'`

RX=`echo "scale = 0; ($RX2-$RX1)/$DLY" | bc -l`
TX=`echo "scale = 0; ($TX2-$TX1)/$DLY" | bc -l`
AX=`echo "scale = 0; $RX+$TX" | bc -l`

if [ "$UNIT" = "" ]; then
  if [ "$RX" -ge 102400 -o "$TX" -ge 102400 ]; then
    FAC=1048576
    case "$ULEV"
    in
      0) SUF="";;
      1) SUF="M";;
      2) SUF="MB";;
      3) SUF="M/s";;
      *) SUF="MB/s";;
    esac
  elif [ "$RX" -ge 100 -o "$TX" -ge 100 ]; then
    FAC=1024
    case "$ULEV"
    in
      0) SUF="";;
      1) SUF="K";;
      2) SUF="KB";;
      3) SUF="K/s";;
      *) SUF="KB/s";;
    esac
  else
    FAC=1
    case "$ULEV"
    in
      0) SUF="";;
      1) SUF="B";;
      2) SUF="B";;
      *) SUF="B/s";;
    esac
  fi
fi

RN=`echo $RX/$FAC | bc -l | awk '{ x = sprintf("%.1f", $1); print x }'`
TN=`echo $TX/$FAC | bc -l | awk '{ x = sprintf("%.1f", $1); print x }'`
AN=`echo $AX/$FAC | bc -l | awk '{ x = sprintf("%.1f", $1); print x }'`

if [ "$RT" = "up" ]; then
  echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> $TN$SUF</span><span color=\"${LABEL_COLOR}\"> ${UP}</span>"
elif [ "$RT" = "down" -o "$RT" = "dn" ]; then
  echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> $RN$SUF</span><span color=\"${LABEL_COLOR}\"> ${DN}</span>"
elif [ "$RT" = "total" ]; then
  echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> $AN$SUF</span>"
else
  if [ "$SEP" = "" ]; then
    if [ "$LABEL" = false ]; then
      echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> $RN$SUF $TN$SUF</span>"
    else
  echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> $RN$SUF</span><span color=\"${LABEL_COLOR}\"> ${DN} </span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">$TN$SUF</span><span color=\"${LABEL_COLOR}\"> ${UP}</span>"
    fi
  else
    if [ "$LABEL" = false ]; then
      echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\"> $RN$SUF $SEP $TN$SUF</span>"
    else
  echo "<span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">
  $RN$SUF</span><span color=\"${LABEL_COLOR}\"> ${DN} </span><span font_desc=\"${VALUE_FONT}\" color=\"${VALUE_COLOR}\">$SEP $TN$SUF</span><span color=\"${LABEL_COLOR}\"> ${UP}</span>"
    fi
  fi
fi
```

It looks like this and seems to give some stats but I haven't spent any time to verify the values.  

image

**Comment by kgilmer** [comment]
And here is my i3xrocks config:
```
# i3xrocks config file
# # The man page for i3blocks is hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=/usr/share/i3xrocks/$BLOCK_NAME
separator_block_width=40
markup=pango
color=xresource:i3xrocks.value.color
label_color=xresource:i3xrocks.label.color

# Network manager VPN
#
# Displays currently connected VPN using the nm-cli tool.
#[nm-vpn]
#interval=5

# Wifi
#
# Displays the wifi network's name
# If the auto-discovered wifi device is incorrect,
# override the "instance" value with the desired device
[wifi2]
#instance=wlp3s0 Replace with your wifi device if you need
interval=5

# Keyboard layout
#
# Displays current keyboard layout.
#[keyboard_layout]
#interval=persist

# CPU usage
#
# The script may be called with -w and -c switches to specify thresholds,
# see the script for details.
[cpu_usage]
interval=5
min_width=100%
#separator=false

# Battery indicator
#
# Displays total percentage charge left across all batteries.
#
# To display colored text (or icon, if "icon_only" is enabled)
# depending on charge remaining, uncomment "percent_color".
#
# To display est. time remaining, uncomment "display_time_left".
#
# To display the battery icon only, uncomment "icon_only".
[battery2]
interval=30
#display_time_left=true
percent_color=true
#icon_only=true

[nettraffic]
command=/tmp/nettraffic/nettraffic_kg
interval=10

# Date Time
#
[time]
interval=60

```

**Comment by cheginit** [comment]
@kgilmer Great! It seems to work properly now. I tested it with fast.com and it shows the correct value. Though the interval is better to be a low value like 2.

**Comment by kgilmer** [comment]
Looks good @cheginit .  I notice that the character count varies depending on network usage so it makes the bar text move in a distracting way.  Other blockets do this too though so I wouldn't hold the merge up for that.  What would you like to do, merge now or format the values so that they always take up a constant number of characters on the bar?

**Comment by kgilmer** [comment]
Also, it would be good to have a prefix icon that explains what the data is for.  Something that conveys network bandwidth.  You'll notice that the other blockets also have this leading icon.

**Comment by kgilmer** [comment]
Also, I notice that when my laptop first wakes up, it has not connected to the wifi yet, I see "No Interface Specified" which takes up a lot of space.  I think it would be better if there was nothing, or maybe an alternate icon that signifies no network.

**Comment by cheginit** [comment]
@kgilmer I made all the changes that you suggested. I added the wifi2 block to this block so it can be replaced with that one altogether. In case there is no wifi (i.e., ethernet), its icon and essid will not be shown just the speeds.

**Comment by kgilmer** [comment]
I'm running your latest version on my desktop and it's working as expected.  I like the idea of consolidating the wifi and bandwidth info, but IMHO it's better to keep them as separate blockets as that provides more options to users wishing to have finer control on what they display on the bar.  Also, I think the wifi icon and ESID name should occur before the bandwidth data.  It reads from left-to-right and the general structure is [icon] [text] for all blockets and I'd like to keep it that way unless there is value in changing it.  Thoughts?

image

**Comment by kgilmer** [comment]
The triangles you have are good but feel a bit heavy.  Maybe this might be a bit lighter?



U+F0D7 <Private Use>

General Character Properties

In Unicode since: 1.1
Unicode category: Other, Private Use

Various Useful Representations

UTF-8: 0xEF 0x83 0x97
UTF-16: 0xF0D7

C octal escaped UTF-8: \357\203\227
XML decimal entity: &#61655;

image

**Comment by kgilmer** [comment]
You may have something else in mind, but if not this may be a good "network" icon as provided by fontawesome:

image

**Comment by cheginit** [comment]
> `[bandwidth icon] [download rate] [download icon] [upload rate] [upload icon]`

Sounds reasonable. I will implement it.

**Comment by cheginit** [comment]
> The triangles you have are good but feel a bit heavy. Maybe this might be a bit lighter?
> 
> 
> 
> U+F0D7
> 
> General Character Properties
> 
> In Unicode since: 1.1
> Unicode category: Other, Private Use
> 
> Various Useful Representations
> 
> UTF-8: 0xEF 0x83 0x97
> UTF-16: 0xF0D7
> 
> C octal escaped UTF-8: \357\203\227
> XML decimal entity: 

As a matter of fact, I did consider this one but in the end, I decided against it since it is very small and when you use this upload and download icon in a line they are hardly distinguishable, specifically on a laptop. What do you think?

**Comment by cheginit** [comment]
> You may have something else in mind, but if not this may be a good "network" icon as provided by fontawesome:
> 
> image

I think we can have separate icons for wifi and ethernet, this one for ethernet and the original one for wifi, what do you think?

**Comment by cheginit** [comment]
The following lines needs to be added to style files:
`typeface-*` :
```
#define typeface_bar_glyph_wired 
#define typeface_bar_glyph_up ▴
#define typeface_bar_glyph_dn ▾
```

`i3xrocks`:
```
i3xrocks.label.wired: typeface_bar_glyph_wired
i3xrocks.label.up: typeface_bar_glyph_up
i3xrocks.label.dn: typeface_bar_glyph_dn
```

**Comment by kgilmer** [comment]
Fantastic work @cheginit !

**Comment by cheginit** [comment]
Great!

**Pull request merged**
