### PR TITLE
microphone status indicator from Niclas Lopez

### PR DESCRIPTION
**Pull request by kgilmer**
Take nicolas-lopez's contribution via gist as microphone status indicator.  Related to https://github.com/regolith-linux/regolith-i3xrocks-config/issues/105.

### CODE REVIEW

**Review by cheginit — CHANGES_REQUESTED** [review]
Just a minor thing, use JetBrains Mono as the default font instead of Source Code Pro.

**Comment by moritzheiber** [comment]
Sorry for not responding earlier .. as far as I can see this is a carbon copy of the volume indicator .. with just a few adjustments for displaying a microphone emoji instead of the volume?

As far as I remember we discussed reworking the volume blocklet the last time and came to the conclusion that it should rather be ported to Pulseaudio. I may be remembering this incorrectly though.

**Comment by jc00ke** [comment]
Is this PR even necessary anymore? Looks like this script [already exists](https://github.com/regolith-linux/regolith-i3xrocks-config/blob/f5fcb40ff123b3d8d45e579f6146acee7d988854/scripts/microphone) minus the default font, which most are `Source Code Pro` anyway (only `memory` and `media-player` default to `JetBrains Mono`).

**Comment by kgilmer** [comment]
Yes this should be closed, thanks @jc00ke !

**Pull request closed without merging**
