### PR TITLE
Add todo blocklet

### PR DESCRIPTION
**Pull request by cheginit**
The required config file for todo.

### CODE REVIEW

**Comment by kgilmer** [comment]
You'll need to add a package description for this as well.  You'll need to add a stanza to debian/control, similiar to:

```
Package: i3xrocks-focused-window-name
Architecture: any
Depends: ${misc:Depends},
    python3 (>= 3.5),
    regolith-i3xrocks-config,
    i3ipc-python
Description: Indicator to show focused window name.
 An i3xrocks indicator to show the name of the focused window.
```

and an install file, similar to `debian/i3xrocks-cpu-usage.install`.

**Comment by cheginit** [comment]
@kgilmer What can we do about `todo` script? For now, I copied it from the todo repo but I guess there should be another way to install it.

**Comment by cheginit** [comment]
@kgilmer Also, where should I add the icon?
```bash
i3xrocks.label.todo: 
```

**Comment by kgilmer** [comment]
@cheginit the `todo` script is the same as `td-cli`?  Or the i3xrocks script?

**Comment by kgilmer** [comment]
The icon will need to be added to all the styles.  I can help w/ that, it's rather tedious.  In the short term, you can express a default with xrescat so that it will work for the default theme.  Pick a default icon from the material design web icons.

**Comment by cheginit** [comment]
@kgilmer The `todo` script is an i3xrocks script, the one from the new repo that I created for the blocklet.

Regarding the font, this one sounds good:
https://material.io/resources/icons/?icon=format_list_numbered&style=baseline

Yeah, I noticed that there are a couple of potential places hence my question. I wonder if there's a script that can automate it?

**Comment by kgilmer** [comment]
> I wonder if there's a script that can automate it?

Well we could generate the style files from templates.  I guess there is a sweet spot at which doing something like that pays off, but am not sure if we're there yet.  Updating styles to be consistent is one of my least favorite things to do w/ Regolith.

**Comment by cheginit** [comment]
@kgilmer I think this commit is ready to be merged.

**Comment by kgilmer** [comment]
@cheginit I'm ready to push this once you've rebased.

**Comment by cheginit** [comment]
@kgilmer Done!

**Pull request merged**
